### ISSUE TITLE
Support for nested params

### ISSUE THREAD

**Issue by destroytoday** [mattt/sinatra-param#33]
At the moment, there isn't a way to validate nested params. Passing something like `?post[title]=Derp` in Sinatra will convert the param to `post = { title: 'Derp' }`. It'd be very handy to validate it the way it's passed, like:

`param 'post[title]', String, required: true`

**Comment by mkonecny** [comment]
It would be great if we could use `sinatra-param` inside of our models for verification. Right now I am creating two methods for verification (one inside my models and one for the HTTP parameters), when I think this project would handle both cases really well.

**Comment by mattt** [comment]
@mkonecny `sinatra-param` is a replacement for or augmentation for true model validation. If you already have that, just use that instead.

```ruby
if @model.save
   @model.to_json
else
  @model.errors.to_json
end
```

...or the like.

**Comment by pjmartorell** [comment]
Hi! I'm building a Sinatra app that acts as a wrapper for another API and I'm passing nested parameters. I have no ActiveRecord models. It would be nice if we could have this feature 😕

**Comment by mattt** [comment]
@pjmartorell If you're wrapping an external API, I think that's all the more reason to formalize the interface with a proper model. It doesn't have to be ActiveRecord (or even ActiveModel — though that's usually a good fit). You should be able to write tests for what qualifies as valid and invalid model objects separately from interactions with Sinatra / `sinatra-param`.

**Comment by pjmartorell** [comment]
Thanks for your reply, finally I moved to another gem calles Compel (https://github.com/joaquimadraz/compel) which I think fits better for what I need

**Comment by mattt** [comment]
@pjmartorell Glad to hear you found something that works for you!
