### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by rrcobb** [mattt/sinatra-param#45]
I am using bundler, so I put `gem 'sinatra-param', '~> 1.3' in my Gemfile. For those without bundler, it's 'gem install sinatra-param'. Having install details in the readme would probably be helpful!

**Comment by mkonecny** [comment]
The confusion for me was I wasn't sure if this was part of the `sinatra/contrib` gem as many sinatra extensions are. Having this install info documented would resolve that.

**Comment by mattt** [comment]
Fixed by f6fd46c.
