### ISSUE TITLE
Custom Messages

### ISSUE THREAD

**Issue by mikejholly** [mattt/sinatra-param#48]
It would be nice to have support for custom error messages. Maybe something like:

``` ruby
param :foo, required: true, is: 'super-secret-value', message: 'Invalid value for foo'
```

Otherwise, very handy gem. Thanks!

**Comment by brianphillips** [comment]
:+1: would appreciate this as well

**Comment by pavel-jurasek-merck-com** [comment]
👍

**Comment by yovasx2** [comment]
Messages are needed just for "is", cause some different messages are manage along the project (presence, type, format, equality, etc). What kind of messages are you talking about, all of them?
