### ISSUE TITLE
Output as Swagger?

### ISSUE THREAD

**Issue by science** [mattt/sinatra-param#53]
First off, I _love_ this gem. It's such a simple idea, and so useful. As I've been implementing with this gem, I've been thinking that I'm almost completely specifying my API with the [VERB] [PATH] Sinatra call (e.g. `get '/api/element'`), plus my sinatra-param statements.

So, with a bit of introspection, I've been wondering if sinatra-param might be induced to output Swagger syntax or similar if run in a "documenting" mode? I'm not quite sure how this would work, but I _think_ we might do this by setting sinatra-param into "documentation == true" mode, and then running the Sinatra app in a test harness. Sinatra-param would create/hold an in-memory representation of every API call that is made to it (minus dupes)? Then at the end of the test suite, we could ask sinatra-param for that a data structure (json/hash?) of all the unique API calls it has experienced. From there converting to whatever format (e.g. Swagger) and dumping to a file? We'd have documentation for at least every API call that is _tested_ which creates a nice incentive to test every API! :)

This might be overly complicated and/or uninteresting to you, but I wanted to raise the idea, and see what you thought. I'd be willing to pitch in, if you think there is something useful here. 

Thanks again for the great gem, in all cases!

**Comment by mattt** [comment]
Thanks for the kind words, @science. I think this is a really interesting idea and a compelling use case, but probably out of scope for this library.

I haven't thought this all the way through, but you might be able to implement this functionality in a separate gem by monkey-patching the behavior of the `param` method and intercepting the arguments for each endpoint exposed by the Sinatra app.

If you do end up implementing this one way or another, let me know!
