### ISSUE TITLE
BigDecimal support

### ISSUE THREAD

**Issue by tuexss** [mattt/sinatra-param#56]
Are there any plans to support BigDecimal for validation, or should these be taken as String and handled manually?

**Comment by mattt** [comment]
Given the complexity of handling arithmetic overflow and other edge cases, and assuming that most users aren't interacting with large or high-precision math, I'd say that support for `BigDecimal` is currently out of scope for this library.

For now, yes—I'd advise handling these kinds of numbers as strings (possibly using string format validation) and then converting to `BigDecimal` separately.
