### ISSUE TITLE
Check if param exists in database

### ISSUE THREAD

**Issue by skarjoko** [mattt/sinatra-param#61]
Wondering if it's possible to do data verification with this gem, by checking a parameter's value against a column to see if it exists?

Essentially, I want to move the verification out of activerecord into the route itself.

**Comment by mattt** [comment]
Although you could ostensibly accomplish this by passing `YourModel.allowed_values` into a call to `param` with the `in` option, I wouldn't recommend it. This kind of logic would be more appropriate at the model layer.
