### ISSUE TITLE
Any plans to support data in the POST request.body?

### ISSUE THREAD

**Issue by jamietsao** [mattt/sinatra-param#66]
I realize the challenge of creating a generic DSL for an arbitrary request body, but maybe it would be easier if it only supported a JSON body?

**Comment by xuoe** [comment]
There is a simple solution to this. From the README:

> Use sinatra-param in combination with [Rack::PostBodyContentTypeParser](https://github.com/rack/rack-contrib/blob/master/lib/rack/contrib/post_body_content_type_parser.rb) and Rack::NestedParams to automatically parameterize JSON POST bodies and nested parameters.

**Comment by mattt** [comment]
Thanks for your response, @xuoe.

@jamietsao: Let me know if this doesn't answer your question exactly, or if you had any ideas on how to clarify this use case in the README. Thanks!
