### ISSUE TITLE
Add support for Sinatra 2.0

### ISSUE THREAD

**Issue by gonace** [mattt/sinatra-param#82]
Hi
Is it possible to add Sinatra 2.0 support for fo this wounderfull gem?

Regards

**Comment by mattt** [comment]
Apologies for the delay, @gonace. 

Now that I'm able to maintain my open source projects again, adding Sinatra 2.0 support to sinatra-param is a top priority. I'll have a new release cut by the end of the day.

**Comment by mattt** [comment]
Alright, sinatra-param 1.5.0 is now released with support for Sinatra 2.0. 🍾

https://rubygems.org/gems/sinatra-param/versions/1.5.0

Thanks to everyone for your patience.
