### ISSUE TITLE
'09' is not a valid Integer

### ISSUE THREAD

**Issue by AndreiBujenitsa** [mattt/sinatra-param#92]
Type integer doesn't work with parameters such as '09'.

Example:
`param :aid, Integer`

[localhost:3000/?aid=09](url) will return an error:
_'09' is not a valid Integer_

Solution:
https://github.com/mattt/sinatra-param/blob/master/lib/sinatra/param.rb#L95
That line should be changed by 
`return Integer(param, 10) if type == Integer`

**Comment by mattt** [comment]
Fixed by #95. Thanks again, @AndreiBujenitsa.
